# AUTO-GENERATED PERSON_URLS v4 - NO FORBES (use Bloomberg instead!)
# Congress members: OpenSecrets + Ballotpedia + Wikipedia + Bloomberg + Senate/House
# Non-congress: OpenSecrets + Ballotpedia + Wikipedia + Bloomberg
# Congress: 33, Non-Congress: 88

PERSON_URLS = {
    "Adam Schiff": [
        {"url": "https://www.opensecrets.org/search?q=Adam+Schiff", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Adam_Schiff", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Adam+Schiff", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Al Gore": [
        {"url": "https://www.opensecrets.org/search?q=Al+Gore", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Al_Gore", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Al+Gore", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Ali Khamenei": [
        {"url": "https://www.opensecrets.org/search?q=Ali+Khamenei", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Ali_Khamenei", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Ali+Khamenei", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Amy Klobuchar": [
        {"url": "https://www.opensecrets.org/search?q=Amy+Klobuchar", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Amy_Klobuchar", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Amy+Klobuchar", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Andy Kim": [
        {"url": "https://www.opensecrets.org/search?q=Andy+Kim", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Andy_Kim", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Andy+Kim", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Angela Alsobrooks": [
        {"url": "https://www.opensecrets.org/search?q=Angela+Alsobrooks", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Angela_Alsobrooks", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Angela+Alsobrooks", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Angus King": [
        {"url": "https://www.opensecrets.org/search?q=Angus+King", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Angus_King", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Angus+King", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Ashley Moody": [
        {"url": "https://www.opensecrets.org/search?q=Ashley+Moody", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Ashley_Moody", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Ashley+Moody", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Barack Obama": [
        {"url": "https://www.opensecrets.org/search?q=Barack+Obama", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Barack_Obama", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Barack+Obama", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Ben Lujan": [
        {"url": "https://www.opensecrets.org/search?q=Ben+Lujan", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Ben_Lujan", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Ben+Lujan", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Bernie Moreno": [
        {"url": "https://www.opensecrets.org/search?q=Bernie+Moreno", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Bernie_Moreno", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Bernie+Moreno", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Bernie Sanders": [
        {"url": "https://www.opensecrets.org/search?q=Bernie+Sanders", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Bernie_Sanders", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Bernie+Sanders", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Bill Cassidy": [
        {"url": "https://www.opensecrets.org/search?q=Bill+Cassidy", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Bill_Cassidy", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Bill+Cassidy", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Bill Clinton": [
        {"url": "https://www.opensecrets.org/search?q=Bill+Clinton", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Bill_Clinton", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Bill+Clinton", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Bill Hagerty": [
        {"url": "https://www.opensecrets.org/search?q=Bill+Hagerty", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Bill_Hagerty", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Bill+Hagerty", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Brian Schatz": [
        {"url": "https://www.opensecrets.org/search?q=Brian+Schatz", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Brian_Schatz", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Brian+Schatz", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Catherine Cortez Masto": [
        {"url": "https://www.opensecrets.org/search?q=Catherine+Cortez+Masto", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Catherine_Cortez_Masto", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Catherine+Cortez+Masto", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Charles Schumer": [
        {"url": "https://www.opensecrets.org/search?q=Charles+Schumer", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Charles_Schumer", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Charles+Schumer", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Chris Christie": [
        {"url": "https://www.opensecrets.org/search?q=Chris+Christie", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Chris_Christie", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Chris+Christie", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Christopher Coons": [
        {"url": "https://www.opensecrets.org/search?q=Christopher+Coons", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Christopher_Coons", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Christopher+Coons", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Christopher Murphy": [
        {"url": "https://www.opensecrets.org/search?q=Christopher+Murphy", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Christopher_Murphy", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Christopher+Murphy", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Chuck Grassley": [
        {"url": "https://www.opensecrets.org/search?q=Chuck+Grassley", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Chuck_Grassley", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Chuck+Grassley", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Cindy Hyde-Smith": [
        {"url": "https://www.opensecrets.org/search?q=Cindy+Hyde-Smith", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Cindy_Hyde-Smith", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Cindy+Hyde-Smith", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Condoleezza Rice": [
        {"url": "https://www.opensecrets.org/search?q=Condoleezza+Rice", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Condoleezza_Rice", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Condoleezza+Rice", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Cory Booker": [
        {"url": "https://www.opensecrets.org/search?q=Cory+Booker", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Cory_Booker", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Cory+Booker", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Cynthia Lummis": [
        {"url": "https://www.opensecrets.org/search?q=Cynthia+Lummis", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Cynthia_Lummis", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Cynthia+Lummis", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Darrell Issa": [
        {"url": "https://www.opensecrets.org/search?q=Darrell+Issa", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Darrell_Issa", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Darrell+Issa", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "David McCormick": [
        {"url": "https://www.opensecrets.org/search?q=David+McCormick", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/David_McCormick", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=David+McCormick", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Deb Fischer": [
        {"url": "https://www.opensecrets.org/search?q=Deb+Fischer", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Deb_Fischer", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Deb+Fischer", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Donald Trump": [
        {"url": "https://www.opensecrets.org/search?q=Donald+Trump", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Donald_Trump", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Donald+Trump", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Edward Markey": [
        {"url": "https://www.opensecrets.org/search?q=Edward+Markey", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Edward_Markey", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Edward+Markey", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Elissa Slotkin": [
        {"url": "https://www.opensecrets.org/search?q=Elissa+Slotkin", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Elissa_Slotkin", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Elissa+Slotkin", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Elizabeth Warren": [
        {"url": "https://www.opensecrets.org/search?q=Elizabeth+Warren", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Elizabeth_Warren", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Elizabeth+Warren", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Eric Schmitt": [
        {"url": "https://www.opensecrets.org/search?q=Eric+Schmitt", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Eric_Schmitt", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Eric+Schmitt", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Gary Peters": [
        {"url": "https://www.opensecrets.org/search?q=Gary+Peters", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Gary_Peters", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Gary+Peters", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Gavin Newsom": [
        {"url": "https://www.opensecrets.org/search?q=Gavin+Newsom", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Gavin_Newsom", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Gavin+Newsom", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "George W. Bush": [
        {"url": "https://www.opensecrets.org/search?q=George+W.+Bush", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/George_W._Bush", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=George+W.+Bush", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Jack Reed": [
        {"url": "https://www.opensecrets.org/search?q=Jack+Reed", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Jack_Reed", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Jack+Reed", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Jacky Rosen": [
        {"url": "https://www.opensecrets.org/search?q=Jacky+Rosen", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Jacky_Rosen", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Jacky+Rosen", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "James Lankford": [
        {"url": "https://www.opensecrets.org/search?q=James+Lankford", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/James_Lankford", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=James+Lankford", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "James Risch": [
        {"url": "https://www.opensecrets.org/search?q=James+Risch", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/James_Risch", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=James+Risch", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Jared Kushner": [
        {"url": "https://www.opensecrets.org/search?q=Jared+Kushner", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Jared_Kushner", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Jared+Kushner", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Jeanne Shaheen": [
        {"url": "https://www.opensecrets.org/search?q=Jeanne+Shaheen", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Jeanne_Shaheen", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Jeanne+Shaheen", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Jeff Merkley": [
        {"url": "https://www.opensecrets.org/search?q=Jeff+Merkley", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Jeff_Merkley", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Jeff+Merkley", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Jerry Moran": [
        {"url": "https://www.opensecrets.org/search?q=Jerry+Moran", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Jerry_Moran", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Jerry+Moran", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Jim Banks": [
        {"url": "https://www.opensecrets.org/search?q=Jim+Banks", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Jim_Banks", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Jim+Banks", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Joe Biden": [
        {"url": "https://www.opensecrets.org/search?q=Joe+Biden", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Joe_Biden", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Joe+Biden", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "John Barrasso": [
        {"url": "https://www.opensecrets.org/search?q=John+Barrasso", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/John_Barrasso", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=John+Barrasso", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "John Boozman": [
        {"url": "https://www.opensecrets.org/search?q=John+Boozman", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/John_Boozman", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=John+Boozman", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "John Cornyn": [
        {"url": "https://www.opensecrets.org/search?q=John+Cornyn", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/John_Cornyn", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=John+Cornyn", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "John Curtis": [
        {"url": "https://www.opensecrets.org/search?q=John+Curtis", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/John_Curtis", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=John+Curtis", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "John Fetterman": [
        {"url": "https://www.opensecrets.org/search?q=John+Fetterman", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/John_Fetterman", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=John+Fetterman", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "John Hickenlooper": [
        {"url": "https://www.opensecrets.org/search?q=John+Hickenlooper", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/John_Hickenlooper", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=John+Hickenlooper", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "John Hoeven": [
        {"url": "https://www.opensecrets.org/search?q=John+Hoeven", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/John_Hoeven", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=John+Hoeven", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "John Kennedy": [
        {"url": "https://www.opensecrets.org/search?q=John+Kennedy", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/John_Kennedy", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=John+Kennedy", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "John Thune": [
        {"url": "https://www.opensecrets.org/search?q=John+Thune", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/John_Thune", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=John+Thune", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Jon Husted": [
        {"url": "https://www.opensecrets.org/search?q=Jon+Husted", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Jon_Husted", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Jon+Husted", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Jon Ossoff": [
        {"url": "https://www.opensecrets.org/search?q=Jon+Ossoff", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Jon_Ossoff", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Jon+Ossoff", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Joni Ernst": [
        {"url": "https://www.opensecrets.org/search?q=Joni+Ernst", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Joni_Ernst", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Joni+Ernst", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Josh Hawley": [
        {"url": "https://www.opensecrets.org/search?q=Josh+Hawley", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Josh_Hawley", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Josh+Hawley", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Kamala Harris": [
        {"url": "https://www.opensecrets.org/search?q=Kamala+Harris", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Kamala_Harris", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Kamala+Harris", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Katie Britt": [
        {"url": "https://www.opensecrets.org/search?q=Katie+Britt", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Katie_Britt", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Katie+Britt", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Kevin Cramer": [
        {"url": "https://www.opensecrets.org/search?q=Kevin+Cramer", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Kevin_Cramer", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Kevin+Cramer", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Kirsten Gillibrand": [
        {"url": "https://www.opensecrets.org/search?q=Kirsten+Gillibrand", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Kirsten_Gillibrand", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Kirsten+Gillibrand", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Lindsey Graham": [
        {"url": "https://www.opensecrets.org/search?q=Lindsey+Graham", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Lindsey_Graham", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Lindsey+Graham", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Lisa Blunt Rochester": [
        {"url": "https://www.opensecrets.org/search?q=Lisa+Blunt+Rochester", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Lisa_Blunt_Rochester", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Lisa+Blunt+Rochester", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Lisa Murkowski": [
        {"url": "https://www.opensecrets.org/search?q=Lisa+Murkowski", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Lisa_Murkowski", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Lisa+Murkowski", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Liz Cheney": [
        {"url": "https://www.opensecrets.org/search?q=Liz+Cheney", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Liz_Cheney", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Liz+Cheney", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Marco Rubio": [
        {"url": "https://www.opensecrets.org/search?q=Marco+Rubio", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Marco_Rubio", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Marco+Rubio", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Margaret Hassan": [
        {"url": "https://www.opensecrets.org/search?q=Margaret+Hassan", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Margaret_Hassan", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Margaret+Hassan", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Maria Cantwell": [
        {"url": "https://www.opensecrets.org/search?q=Maria+Cantwell", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Maria_Cantwell", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Maria+Cantwell", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Mark Green": [
        {"url": "https://www.opensecrets.org/search?q=Mark+Green", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Mark_Green", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Mark+Green", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Mark Kelly": [
        {"url": "https://www.opensecrets.org/search?q=Mark+Kelly", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Mark_Kelly", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Mark+Kelly", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Mark Warner": [
        {"url": "https://www.opensecrets.org/search?q=Mark+Warner", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Mark_Warner", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Mark+Warner", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Markwayne Mullin": [
        {"url": "https://www.opensecrets.org/search?q=Markwayne+Mullin", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Markwayne_Mullin", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Markwayne+Mullin", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Marsha Blackburn": [
        {"url": "https://www.opensecrets.org/search?q=Marsha+Blackburn", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Marsha_Blackburn", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Marsha+Blackburn", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Martin Heinrich": [
        {"url": "https://www.opensecrets.org/search?q=Martin+Heinrich", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Martin_Heinrich", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Martin+Heinrich", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Mazie Hirono": [
        {"url": "https://www.opensecrets.org/search?q=Mazie+Hirono", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Mazie_Hirono", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Mazie+Hirono", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Michael Bennet": [
        {"url": "https://www.opensecrets.org/search?q=Michael+Bennet", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Michael_Bennet", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Michael+Bennet", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Michelle Obama": [
        {"url": "https://www.opensecrets.org/search?q=Michelle+Obama", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Michelle_Obama", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Michelle+Obama", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Mike Bloomberg": [
        {"url": "https://www.opensecrets.org/search?q=Mike+Bloomberg", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Mike_Bloomberg", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Mike+Bloomberg", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Mike Crapo": [
        {"url": "https://www.opensecrets.org/search?q=Mike+Crapo", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Mike_Crapo", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Mike+Crapo", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Mike Lee": [
        {"url": "https://www.opensecrets.org/search?q=Mike+Lee", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Mike_Lee", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Mike+Lee", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Mike Pence": [
        {"url": "https://www.opensecrets.org/search?q=Mike+Pence", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Mike_Pence", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Mike+Pence", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Mike Rounds": [
        {"url": "https://www.opensecrets.org/search?q=Mike+Rounds", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Mike_Rounds", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Mike+Rounds", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Mitch McConnell": [
        {"url": "https://www.opensecrets.org/search?q=Mitch+McConnell", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Mitch_McConnell", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Mitch+McConnell", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Moore Capito": [
        {"url": "https://www.opensecrets.org/search?q=Moore+Capito", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Moore_Capito", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Moore+Capito", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Nancy Pelosi": [
        {"url": "https://www.opensecrets.org/search?q=Nancy+Pelosi", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Nancy_Pelosi", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Nancy+Pelosi", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Nikki Haley": [
        {"url": "https://www.opensecrets.org/search?q=Nikki+Haley", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Nikki_Haley", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Nikki+Haley", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Patty Murray": [
        {"url": "https://www.opensecrets.org/search?q=Patty+Murray", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Patty_Murray", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Patty+Murray", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Pete Ricketts": [
        {"url": "https://www.opensecrets.org/search?q=Pete+Ricketts", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Pete_Ricketts", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Pete+Ricketts", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Peter Welch": [
        {"url": "https://www.opensecrets.org/search?q=Peter+Welch", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Peter_Welch", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Peter+Welch", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Rand Paul": [
        {"url": "https://www.opensecrets.org/search?q=Rand+Paul", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Rand_Paul", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Rand+Paul", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Raphael Warnock": [
        {"url": "https://www.opensecrets.org/search?q=Raphael+Warnock", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Raphael_Warnock", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Raphael+Warnock", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Rich McCormick": [
        {"url": "https://www.opensecrets.org/search?q=Rich+McCormick", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Rich_McCormick", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Rich+McCormick", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Richard Blumenthal": [
        {"url": "https://www.opensecrets.org/search?q=Richard+Blumenthal", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Richard_Blumenthal", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Richard+Blumenthal", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Richard Durbin": [
        {"url": "https://www.opensecrets.org/search?q=Richard+Durbin", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Richard_Durbin", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Richard+Durbin", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Rick Scott": [
        {"url": "https://www.opensecrets.org/search?q=Rick+Scott", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Rick_Scott", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Rick+Scott", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Robert F. Kennedy Jr.": [
        {"url": "https://www.opensecrets.org/search?q=Robert+F.+Kennedy+Jr.", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Robert_F._Kennedy_Jr.", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Robert+F.+Kennedy+Jr.", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Roger Marshall": [
        {"url": "https://www.opensecrets.org/search?q=Roger+Marshall", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Roger_Marshall", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Roger+Marshall", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Roger Wicker": [
        {"url": "https://www.opensecrets.org/search?q=Roger+Wicker", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Roger_Wicker", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Roger+Wicker", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Ron DeSantis": [
        {"url": "https://www.opensecrets.org/search?q=Ron+DeSantis", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Ron_DeSantis", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Ron+DeSantis", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Ron Johnson": [
        {"url": "https://www.opensecrets.org/search?q=Ron+Johnson", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Ron_Johnson", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Ron+Johnson", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Ron Wyden": [
        {"url": "https://www.opensecrets.org/search?q=Ron+Wyden", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Ron_Wyden", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Ron+Wyden", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Ronald Reagan": [
        {"url": "https://www.opensecrets.org/search?q=Ronald+Reagan", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Ronald_Reagan", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Ronald+Reagan", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Ruben Gallego": [
        {"url": "https://www.opensecrets.org/search?q=Ruben+Gallego", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Ruben_Gallego", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Ruben+Gallego", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Sen Hawley": [
        {"url": "https://www.opensecrets.org/search?q=Sen+Hawley", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Sen_Hawley", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Sen+Hawley", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Shelley Capito": [
        {"url": "https://www.opensecrets.org/search?q=Shelley+Capito", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Shelley_Capito", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Shelley+Capito", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Steve Daines": [
        {"url": "https://www.opensecrets.org/search?q=Steve+Daines", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Steve_Daines", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Steve+Daines", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Susan Collins": [
        {"url": "https://www.opensecrets.org/search?q=Susan+Collins", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Susan_Collins", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Susan+Collins", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Tammy Baldwin": [
        {"url": "https://www.opensecrets.org/search?q=Tammy+Baldwin", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Tammy_Baldwin", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Tammy+Baldwin", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Ted Budd": [
        {"url": "https://www.opensecrets.org/search?q=Ted+Budd", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Ted_Budd", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Ted+Budd", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Ted Cruz": [
        {"url": "https://www.opensecrets.org/search?q=Ted+Cruz", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Ted_Cruz", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Ted+Cruz", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Thom Tillis": [
        {"url": "https://www.opensecrets.org/search?q=Thom+Tillis", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Thom_Tillis", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Thom+Tillis", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Tim Kaine": [
        {"url": "https://www.opensecrets.org/search?q=Tim+Kaine", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Tim_Kaine", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Tim+Kaine", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Tim Scott": [
        {"url": "https://www.opensecrets.org/search?q=Tim+Scott", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Tim_Scott", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Tim+Scott", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Tim Sheehy": [
        {"url": "https://www.opensecrets.org/search?q=Tim+Sheehy", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Tim_Sheehy", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Tim+Sheehy", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
        {"url": "https://www.senate.gov/senators/", "label": "U.S. Senate/House – Members Directory"},
    ],
    "Tina Smith": [
        {"url": "https://www.opensecrets.org/search?q=Tina+Smith", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Tina_Smith", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Tina+Smith", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Tom Cotton": [
        {"url": "https://www.opensecrets.org/search?q=Tom+Cotton", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Tom_Cotton", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Tom+Cotton", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Tommy Tuberville": [
        {"url": "https://www.opensecrets.org/search?q=Tommy+Tuberville", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Tommy_Tuberville", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Tommy+Tuberville", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
    "Vivek Ramaswamy": [
        {"url": "https://www.opensecrets.org/search?q=Vivek+Ramaswamy", "label": "OpenSecrets – Financial Disclosures"},
        {"url": "https://ballotpedia.org/Vivek_Ramaswamy", "label": "Ballotpedia – Political Profile"},
        {"url": "https://en.wikipedia.org/w/index.php?search=Vivek+Ramaswamy", "label": "Wikipedia – Search"},
        {"url": "https://www.bloomberg.com/", "label": "Bloomberg – Financial Analysis"},
    ],
}
